# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81f3bc0df436c14eec0742c9bf38c228f88b08f60cfab30f1893d8da5e64f1ec6bc1fdd9909a6a70e84adb024a7925c1063f12b380a7ffa8a0d996fd9495f028

test:
  secret_key_base: ab986affaa4d703748f4fe177f1f59776271a1189f583500161b90a32929e7900ff765cb4e6fa5a9c1afb3f7882eeb0415e16fe32645fe2220be27079c8007eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
